image: docker:latest

stages:
  - build

build & push:
  stage: build
  before_script:
    - docker login -u $KODALITY_NEXUS_USER -p $KODALITY_NEXUS_PASSWORD docker.kodality.com
  script:
    - docker build -t docker.kodality.com/fhir-ig-mpi .
    - docker push docker.kodality.com/fhir-ig-mpi
  only:
    - master
